# Generated by Django 3.1.4 on 2022-02-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20220223_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='slug',
            new_name='page_slug',
        ),
    ]
