# Generated by Django 3.1.4 on 2022-02-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20220223_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
