# Generated by Django 3.1.4 on 2022-02-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20220223_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='label',
            new_name='title',
        ),
    ]
