# Generated by Django 5.0.4 on 2024-09-22 14:48

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=core.utils.generate_model_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('item_id', models.CharField(editable=False, max_length=32, null=True)),
                ('name', models.CharField(max_length=250)),
                ('item_settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=25)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item_id'], name='item_index')],
            },
        ),
    ]
