# Generated by Django 3.1.4 on 2022-02-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
